openapi: '3.0.0'
info:
  title: Unlock Locksmith
  version: '2'
  description: Locksmith provides backend functionality for enabling ticketing, metadata storage, and notification hooks.
  license:
    name: MIT

servers:
  - url: https://locksmith.unlock-protocol.com
    description: Production Server
  - url: https://staging-locksmith.unlock-protocol.com
    description: Staging Server

components:
  securitySchemes:
    User:
      type: http
      scheme: bearer
      bearerFormat: JWT
    Application:
      type: apiKey
      name: api-key
      in: query

paths:
  /v2/auth/nonce:
    get:
      description: 'Provide a unique nounce for using in sign in with ethereum'
      parameters: []
      responses:
        '200':
          description: OK
  /v2/auth/login:
    post:
      description: 'Login as a user using Sign in with Ethereum message signed by the wallet address.'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                message:
                  type: string
                signature:
                  type: string
      responses:
        '200':
          description: OK
  /v2/api/{network}/locks/{lockAddress}/keys:
    get:
    parameters:
      - in: path
        name: network
        required: true
        schema:
          type: integer
        description: Network id
      - in: path
        name: lockAddress
        required: true
        schema:
          type: string
        description: Lock address
      description: List of lock keys by network with additional metadata if the caller is the lockManager
      requestBody:
        content:
          application/json:
            schema:
              properties:
                query:
                  type: string
                filterKey:
                  type: string
                expiration:
                  type: string
                page: 
                  type: integer
      responses:
        '200':
          description: List of keys matching the query
          content:
            application/json:
              schema:
                type: array
