name: Check networks package

on:
  workflow_call:

jobs:
  coverage:
    name: Run checks for the networks package
    runs-on: ubuntu-22.04
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: yarn
        shell: bash

      - run: yarn build
        shell: bash

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            packages/networks/src/networks/**

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo ${ALL_CHANGED_FILES}
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - name: Validate networks
        id: validate
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          yarn workspace @unlock-protocol/networks validate 1> results.txt
        shell: bash

      - name: Log Results
        id: log-results
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          cat results.txt
        shell: bash

      - name: Add PR Comment
        if: ${{ always() && steps.changed-files.outputs.any_changed == 'true' }}
        uses: mshick/add-pr-comment@v2.8.2
        with:
          preformatted: true
          message-path: results.txt
          update-only: true
          refresh-message-position: true
