name: Deploy on Railway

on:
  workflow_call:
    inputs:
      service:
        description: 'The service/app to build'
        type: string
        required: true
      service-id:
        description: 'The Railway service ID to deploy to'
        type: string
        required: true
      bypass_diff_check:
        description: 'Bypass the monorepo diff check'
        required: false
        type: string
    secrets:
      railway-token:
        required: true
      OP_SERVICE_ACCOUNT_TOKEN:
        required: true

jobs:
  deploy-to-railway:
    name: Deploy ${{ inputs.service }} on Railway
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.railway-token }}
      SVC_ID: ${{ inputs.service-id }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Load secrets from 1Password
        uses: 1Password/load-secrets-action@v2.0.0
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          RAILWAY_TOKEN: ${{ secrets.railway-token }}
          SVC_ID: ${{ inputs.service-id }}
      - run: railway up --service=${{ env.SVC_ID }}
