name: 'Production Branch'

on:
  push:
    branches:
      - production

jobs:
  deploy-all-subgraphs:
    if: ${{ github.repository_owner == 'unlock-protocol' }}
    uses: ./.github/workflows/_subgraph.yml
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

  deploy-locksmith-production:
    if: ${{ github.repository_owner == 'unlock-protocol' }}
    uses: ./.github/workflows/_heroku.yml
    with:
      bypass_diff_check: bypass
      service: locksmith
      app-name: unlock-locksmith-production
    secrets:
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

  # Netlify Deployments
  deploy-paywall-app-production:
    if: ${{ github.repository_owner == 'unlock-protocol' }}
    uses: ./.github/workflows/_netlify.yml
    with:
      bypass_diff_check: bypass
      service: paywall-app
      target-env: prod
    secrets:
      SITE_ID: ${{ secrets.PAYWALL_APP_NETLIFY_PROD_SITE_ID }}
      AUTH_TOKEN: ${{ secrets.PAYWALL_APP_NETLIFY_PROD_AUTH_TOKEN }}

  deploy-wedlocks:
    if: ${{ github.repository_owner == 'unlock-protocol' }}
    uses: ./.github/workflows/_netlify.yml
    with:
      service: wedlocks
      target-env: prod
      bypass_diff_check: bypass
    secrets:
      SITE_ID: ${{ secrets.WEDLOCKS_NETLIFY_PROD_SITE_ID }}
      AUTH_TOKEN: ${{ secrets.WEDLOCKS_NETLIFY_PROD_AUTH_TOKEN }}
      SMTP_HOST: ${{ secrets.WEDLOCKS_NETLIFY_PROD_SMTP_HOST }}
      SMTP_USERNAME: ${{ secrets.WEDLOCKS_NETLIFY_PROD_SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.WEDLOCKS_NETLIFY_PROD_SMTP_PASSWORD }}
      BASE64_WEDLOCKS_PRIVATE_KEY: ${{ secrets.WEDLOCKS_NETLIFY_PROD_BASE64_WEDLOCKS_PRIVATE_KEY }}

  deploy-unlock-app-vercel:
    if: ${{ github.repository_owner == 'unlock-protocol'  }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Load secrets from 1Password
        uses: 1Password/load-secrets-action@v2.0.0
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          UNLOCK_APP_VERCEL_PROD_VERCEL_PROJECT_ID: op://secrets/vercel/project-id-unlock-app-prod
          UNLOCK_APP_VERCEL_PROD_VERCEL_ORG_ID: op://secrets/vercel/org-id
          UNLOCK_APP_VERCEL_PROD_VERCEL_TOKEN: op://secrets/vercel/deployment-token
          UNLOCK_APP_VERCEL_PROD_NEXT_PUBLIC_BASE64_WEDLOCKS_PUBLIC_KEY: op://secrets/wedlocks/public-key
          UNLOCK_APP_VERCEL_PROD_NEXT_PUBLIC_STRIPE_KEY: op://secrets/stripe/publishable-key-prod
          UNLOCK_APP_VERCEL_PROD_NEXT_PUBLIC_ETHPASS_KEY: op://secrets/ethpass/username
          UNLOCK_APP_VERCEL_PROD_NEXT_PUBLIC_UNLOCK_ENV: prod
          UNLOCK_APP_VERCEL_PROD_GOOGLE_CLIENT_SECRET: op://secrets/google/prod-secret
          UNLOCK_APP_VERCEL_PROD_NEXTAUTH_SECRET: op://secrets/nextauth/prod-secret
      - uses: ./.github/actions/vercel
        with:
          service: unlock-app
          target-env: prod
        env:
          UNLOCK_APP_VERCEL_PROD_NEXTAUTH_URL: 'https://app.unlock-protocol.com'
