name: 'Open weekly production pull request'
on:
  schedule:
    - cron: '30 12 * * 2'
jobs:
  prod-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Open production PR"
        run: scripts/automated-production-pr.sh